### ISSUE TITLE
[Feature]: Documentation foe S3 cache for k8sgpt operator missing secret keys expected.

### ISSUE THREAD

**Issue by qdrddr** [k8sgpt-ai/docs#96]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

On this doc page, no Cache S3 is mentioned at all.
https://docs.k8sgpt.ai/getting-started/in-cluster-operator/

On this 

in this section you should explain that the secret: k8sgpt-sample-cache-secret expects these kyes to be present for s3: `aws_access_key_id` & `aws_secret_access_key`:

[README.md](https://github.com/k8sgpt-ai/k8sgpt-operator/blob/main/README.md)

3. Apply the K8sGPT configuration object:
```
kubectl apply -f - << EOF
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  ai:
    model: gpt-3.5-turbo
    backend: openai
    enabled: true
    secret:
      name: k8sgpt-sample-secret
      key: openai-api-key
  noCache: false
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.3.8
  remoteCache:
    credentials:
      name: k8sgpt-sample-cache-secret
    s3:
      bucketName: foo
      region: us-west-1
EOF
```

### Solution Description

Modify to:

3. Apply the K8sGPT configuration object:
```
kubectl apply -f - << EOF
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  ai:
    model: gpt-3.5-turbo
    backend: openai
    enabled: true
    secret:
      name: k8sgpt-sample-secret
      key: openai-api-key
  noCache: false
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.3.8
  remoteCache:
    credentials:
      name: k8sgpt-sample-cache-secret
      #!These kyes should be present in the secret for s3!
      #aws_access_key_id
      #aws_secret_access_key
    s3:
      bucketName: foo
      region: us-west-1
EOF
```

### Benefits

easy to understand

### Potential Drawbacks

n/a
